name             'app_solr'
maintainer       'Earth U'
maintainer_email 'iskitingbords@gmail.com'
license          'Apache-2.0'
description      'Installs/Configures app_solr'
issues_url       'https://github.com/nollieheel/app_solr/issues'
source_url       'https://github.com/nollieheel/app_solr'
version          '1.1.0'

chef_version '>= 16.0'
supports     'ubuntu', '20.04'
